language: android
android:
 components:
  - build-tools-23.0.1
  - android-23
  - android-21
  - add-on
  - extra
  - platform-tools
  - tools
  - extra-google-googleplaservices
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-android-21
script: ./gradlew :app:build